### ISSUE TITLE
[12] cannot import timesheet

### ISSUE THREAD

**Issue by supakornkim** [OCA/timesheet#385] opened 2020-09-16 00:21 UTC
error message

null value in column "name" violates not-null constraint DETAIL: Failing row contains (195, null, 2020-09-19, 0.0, 6, 6, 21, null, 2, 12, null, null, 2, 2020-09-16 00:20:00.40634, 2, 2020-09-16 00:20:00.40634, null, null, null, null, null, null, null, 22, null, null, null, null, null, null). at row 2

**Comment by pedrobaeza** [comment] 2020-09-16 07:42
The import file shouldn't be correct, but it's not a bug of the module, so closing. Ask for further help on Odoo forums, but you should give more information.

**Closed as completed by pedrobaeza** 2020-09-16 07:42 UTC

**Comment by supakornkim** [comment] 2020-09-16 09:34
the excel i just export from the current record one.
as I checked from the log, it is error when insert to table account_analytic_line.

2020-09-16 09:32:07,318 1 ERROR devdb odoo.sql_db: bad query: INSERT INTO "account_analytic_line" ("id", "create_uid", "create_date", "write_uid", "write_date", "account_id", "amount", "company_id", "date", "employee_id", "product_uom_id", "project_id", "unit_amount", "user_id") VALUES (nextval('account_analytic_line_id_seq'), 2, (now() at time zone 'UTC'), 2, (now() at time zone 'UTC'), 21, 0.0, 12, '2020-09-14', NULL, 6, 22, 6.0, 2) RETURNING id
web_1      | ERROR: null value in column "name" violates not-null constraint

I suspect it may because "name" does not computed correctly from hr.timesheet.sheet ?

in the excel file, i already input date from and date to. as i check from the code that field name is generated from these 2 fields.
