### ISSUE TITLE
[8.0] hr_timesheet_task - Error in runbot hr-timesheet when adding work in task

### ISSUE THREAD

**Issue by rafaelbn** [OCA/timesheet#50] opened 2015-08-11 14:05 UTC
In https://runbot.odoo-community.org/runbot/repo/github-com-oca-hr-timesheet-117
- Create a project
- Create a task
- In the task **click** on "Add an item" to add time of work
- Get this error:

"  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3111498-8-0-d13d5c/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
TypeError: on_change_user_id() takes at least 6 arguments (5 given)"

**Comment by rafaelbn** [comment] 2015-08-11 15:39
Hi @nbessi , who merged this module? I can't test this module hr_timesheet_task as error above.
I suppose when this module was merged error didn't exits.
Any idea? Thanks

cc @gurneyalex

**Comment by nbessi** [comment] 2015-08-12 13:01
@rafaelbn  yes there is a regression due to a modification of fields structure in the core. This issue is a duplicate of #34.

**Closed as completed by nbessi** 2015-08-12 13:01 UTC
