### ISSUE TITLE
[12.0] Timesheet new leave requests not loaded

### ISSUE THREAD

**Issue by CasVissers-360ERP** [OCA/timesheet#303] opened 2020-01-08 07:28 UTC
When creating a timesheet, analytic lines are loaded one-time using _compute_timesheet_ids. If the user finds the timesheet to be missing a leave and requests/approves an additional leave. The timesheet has to be removed an re-created for the leave-timesheet lines to be shown. 

Is this functionality meant to be this way?

**Comment by astirpe** [comment] 2020-01-09 13:13
The module was implemented this way: once the timesheet sheet is approved, no timesheet lines (account.analytic.line) can be added anymore. A new leave would generate a new account.analytic.line, but if the timesheet sheet is approved, it would not be displayed.

So the answer to your question

> Is this functionality meant to be this way?

is yes.

You can always propose a change request in case you need a different behavior and see if there's enough consent...

**Comment by CasVissers-360ERP** [comment] 2020-01-09 13:57
@astirpe But it also doesn't add lines if the timesheet is not approved?

**Comment by astirpe** [comment] 2020-01-09 14:05
Also when is requested to be approved

**Comment by alexey-pelykh** [comment] 2020-02-08 12:28
I guess we can close this one as it's by design, set of timesheets lines are modifiable only in `new` and `draft` state. Please feel free to reopen if needed.

**Closed as completed by alexey-pelykh** 2020-02-08 12:28 UTC

**Comment by CasVissers-360ERP** [comment] 2020-02-25 07:50
I still feel there should be an extra method created to add new approved leave request to already created draft timesheets. But since nobody agrees I think it's better to close the ticket.
