### ISSUE TITLE
timesheet_task

### ISSUE THREAD

**Issue by sysadminmatmoz** [OCA/timesheet#34] opened 2015-05-12 12:12 UTC
Fresh install (OCA odoo), when trying to encode work done:

```
Traceback (most recent call last):
  File "/opt/openerp/fullodoo/__base__/odoo/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/openerp/fullodoo/__base__/odoo/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/openerp/fullodoo/__base__/odoo/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/openerp/fullodoo/__base__/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/openerp/fullodoo/__base__/odoo/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/openerp/fullodoo/__base__/odoo/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/openerp/fullodoo/__base__/odoo/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/openerp/fullodoo/__base__/odoo/addons/web/controllers/main.py", line 936, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/openerp/fullodoo/__base__/odoo/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/openerp/fullodoo/__base__/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/openerp/fullodoo/__base__/odoo/openerp/api.py", line 363, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/openerp/fullodoo/__base__/odoo/openerp/models.py", line 5858, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/opt/openerp/fullodoo/__base__/odoo/openerp/models.py", line 5776, in _onchange_eval
    method_res = getattr(self._model, method)(*args)
  File "/opt/openerp/fullodoo/__base__/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
TypeError: on_change_user_id() takes at least 6 arguments (5 given)
```

If you need any further data, just tell.

**Comment by franckLG** [comment] 2015-05-18 13:29
Hi,
 I get the same issue when trying to add time to a project task. 
i use odoo version of last night

Franck

**Comment by nbessi** [comment] 2015-05-18 13:35
Hello,

Thanks for reporting.  
Can you specify the version of Odoo you used and the branch you used. 
Also when you talk about OCA odoo do you mean https://github.com/OCA/OCB ?

**Comment by franckLG** [comment] 2015-05-18 14:20
On my side I use the Odoo 8.0 available as a Debian package on odoo server

**Comment by gurneyalex** [comment] 2015-05-18 15:04
I see no definition of `on_change_user_id` in timesheet_task or any other addon in this project. 

OTOH https://github.com/odoo/odoo/blob/8.0/addons/hr_timesheet/hr_timesheet.py#L194 -> no context argument, this is weird.

**Comment by franckLG** [comment] 2015-05-18 21:33
I tried to reproduce the problem by starting again with a backup of my database + running an update (-u all) and the problem disappeared.
It thus looks like that this issue is due to a non-uptaded installation and is not a bug.

**Comment by sysadminmatmoz** [comment] 2015-05-19 03:44
The problem persists in my case (https://github.com/OCA/OCB); tried it on a virgin DB too (so no update issue) and on 3 different servers (all OCB git) - I'll try to dig out some more when I have more time.

**Comment by gurneyalex** [comment] 2015-05-19 06:20
@sysadminmatmoz @franckLG can you paste the output of the following SQL query against your database here:

    select name, state from ir_module_module where name like 'hr%' order by name;

**Comment by gurneyalex** [comment] 2015-05-19 06:25
> I see no definition of `on_change_user_id` in timesheet_task or any other addon in this project. 

my bad: https://github.com/OCA/hr-timesheet/blob/8.0/timesheet_task/project_task_view.xml#L12

**Comment by gurneyalex** [comment] 2015-05-19 07:50
@sysadminmatmoz @franckLG 

I am not able to reproduce:
1. I installed OCA/OCB with OCA/hr-timesheet, installed timesheet_task
2. I connect as `admin` on the instance
3. I go to Human Resources -> Timesheet Activities
4. I click on Create
5. on the new line, when I change the user (and there for on_change_user_id is called) nothing bad happens (except that by default the Demo user does not have an analytic account, but this is easily fixed)
6. it also works fine if I connect as `demo`

**Comment by franckLG** [comment] 2015-05-19 07:52
@sysadminmatmoz: Do you have the timesheet modules from Camptocamp installed (hr_timesheet_task, timesheet_task, project_timesheet_analytic). ?
I get the impression that issues are realted to these. I am reinstalling to check

**Comment by sysadminmatmoz** [comment] 2015-05-20 04:49
No c2c modules, just OCA/hr-timesheet
I can repeat all your steps from Human Resources -> Timesheet Activities, the error jumps out only if I try to encode work done on the task form (in the databases from yesterday), in a today's fresh database on a fresh server on the other hand I can't reproduce this issue, but I get the issue https://github.com/OCA/hr-timesheet/issues/33 instead... So there's probably a git rebase inconsistency between my dev servers. I didn't try the module on any of my production servers thou.

I'm sorry that I don't have a chance to dig deeper in it, since it's a busy period for me (it's the main construction season in my region and I can't spend as much time behind my workstation as I would like). Let's hope that the issue is related only to my existent configuration.

**Comment by fescon** [comment] 2015-06-08 12:23
It's definitely related to timesheet_task - as soon as I install this module the error occurs. Try to investigate further.
For some reasons :default_get from hr.analytic.timesheet throws that exception. On a clean install it works. Try to identify the the trigger.

**Comment by franckLG** [comment] 2015-06-11 20:52
In case it can help: I today installed the latest nightly built of Odoo on a Windows and on a Debian. I have the C2C timesheet modules installed in both. With the same database: it works fine under windows. Under Debian I get "RuntimeError: maximum recursion depth exceeded in cmp" :/

**Comment by sterbhai** [comment] 2015-07-11 19:34
Dont know if it helps, and I am not a programmer.
I noticed: project_gtd works fine until I install hr_timesheet_task on the same database. then on create a new task it throws the maximum recusrsion error.
Without the project_gtd task creation works without error. For me its not possible to use the two modules together.
odoo 8 was updated through git pull today; all modules are updated today.

 File "/opt/odoo/openerp/tools/func.py", line 66, in wrapper
    return func(self, _args, *_kwargs)
  File "/opt/odoo/openerp/tools/lru.py", line 44, in **setitem**
    del self[obj]
RuntimeError: maximum recursion depth exceeded while calling a Python object

**Comment by kirca** [comment] 2015-07-29 09:50
It breaks when analytic_user_function is installed since it changes signature to on_change_user_id:
https://github.com/odoo/odoo/blob/8.0/addons/analytic_user_function/analytic_user_function.py#L121
Added a PR which will fix it but adds dependency on analytic_user_function.

**Comment by kirca** [comment] 2015-08-05 22:14
Fixed in https://github.com/odoo/odoo/commit/d1d4688521b919441b4d2e6924df2d21b5046dee

**Comment by rafaelbn** [comment] 2015-08-11 16:48
Hi,

I didn't see this issue (subject is not specific) and this is same issue as https://github.com/OCA/hr-timesheet/issues/50

@kirca says that it is fixed but I have tested today in OCA's runbut and it's still there.

@gurneyalex who can update runbot code to test it again?

Thanks

**Comment by rafaelbn** [comment] 2015-08-12 13:10
Hi @nbessi , Ok but issue is already fixed as @kirca said. When could we test it again in OCA's runbot?

**Closed as completed** 2016-01-28 06:45 UTC
Labels: question, 8.0
